### ISSUE TITLE
concurrent image builds fail due to instance name conflicts

### ISSUE THREAD

**Issue by anarazel** [anarazel/pg-vm-images#13]
If two images are built at the same time, they currently will often fail due to the CI image names conflicting. That's because I (andres) made the image names predictable, to avoid a lot of instances building up in case of failure. But it's likely more confusing than it's worth.  Perhaps we can give instances a shorter max lifetime? And then name them with a recognizable prefix, but a random postfix?

**Comment by nbyavuz** [comment]
I couldn't find a way to set shorter max lifetime(from packer) and for the naming I added date as a postfix. I think instead of using random postfix, date is better; we can understand which image is created from which instance. It could help debugging.

**Comment by anarazel** [comment]
There just was another failure, this time on main, due to the naming conflict. For main, perhaps we could mark the tasks to run in isolation via cirrus? https://cirrus-ci.org/guide/writing-tasks/#task-execution-lock seems like it'd be an improvement, even if not perfect.
