### ISSUE TITLE
switch freebsd to ccache4

### ISSUE THREAD

**Issue by justinpryzby** [anarazel/pg-vm-images#59]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234971

It's the only task using ccache older than 4.  This will enable compression by default.
https://ccache.dev/releasenotes.html

**Comment by anarazel** [comment]
Sounds like a good idea - do you want to open a PR?

**Comment by justinpryzby** [comment]
I'm not planning to do it myself anytime soon...
