### ISSUE TITLE
There are images without a family

### ISSUE THREAD

**Issue by nbyavuz** [anarazel/pg-vm-images#73]
There are images without a family and they may not get cleaned up.

**Comment by nbyavuz** [comment]
It seems the images created by CI gets cleaned up. Could these images have been created by Google itself? Any thoughts @anarazel?

**Comment by anarazel** [comment]
I found only one image without a family, and that was clearly the result of an experiment. I did find a few images that were deprecated and did not get cleaned up. I did so now. But I think the deletion script needs to use the options necessary to see them...

Which images are you referring to?

**Comment by nbyavuz** [comment]
> I found only one image without a family, and that was clearly the result of an experiment. 

I created an image without family and deletion script able to found it.

> I did find a few images that were deprecated and did not get cleaned up. I did so now. But I think the deletion script needs to use the options necessary to see them...

Yes, there is a '--show-deprecated' flag. I will add it.

> Which images are you referring to?

They are images from public image projects, created by Google itself. Like 'debian-cloud, fedora-cloud'.

**Comment by anarazel** [comment]
> They are images from public image projects, added by Google itself. Like 'debian-cloud, fedora-cloud'.

Then we need to use --no-standard-images in the right places...
